server:
  port: 8090

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: Hearing Recordings CVP Ingestor
  config:
    import: "optional:configtree:/mnt/secrets/em-hrs-ingestor/,optional:configtree:/mnt/secrets/em-hrs-api/,optional:configtree:/mnt/secrets/rpa/"
ingestion:
  max-files-to-process: ${MAX_FILES_TO_PROCESS:50}
  cvp:
    process-back-to-day: ${CVP_PROCESS_BACK_TO_DAY:2}
  vh:
    process-back-to-day: ${VH_PROCESS_BACK_TO_DAY:2}

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:d04b52b1-20e5-473a-8ac4-3f6859ea113c}
  storage:
    cvp-storage-connection-string: ${CVP_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1}
    vh-storage-connection-string: ${VH_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1}
    cvp-storage-container-name: ${CVP_STORAGE_CONTAINER_NAME:cvptestcontainer}
    vh-storage-container-name: ${VH_STORAGE_CONTAINER_NAME:vhtestcontainer}
    vh-leased-for-minutes: ${VH_LEASED_FOR_MINUTES:120}
    enabled: true
    use-ad-auth-for-source: ${USE_AD_AUTH_FOR_SOURCE_BLOB_CONNECTION:false}
app-insights:
  dev-mode: on
  request-component: on
  telemetry-component: on

s2s.hrs.api:
  url: ${HRS_API_BASE_URI:http://localhost:8080}


idam:
  s2s-auth:
    url: ${S2S_BASE_URI:http://localhost:4502}
    totp_secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}
    microservice: em_hrs_ingestor

toggle:
  shutdown: ${ENABLE_SHUTDOWN:true}
  cronjob: ${ENABLE_CRONJOB:true}

logging:
  level:
    uk.gov.hmcts.reform.authorisation.filters: DEBUG
