job:
  applicationPort: 8090
  image: 'hmctspublic.azurecr.io/em/hrs-ingestor:latest'
  schedule: "*/15 * * * *"
  # Run every 15 mins during the evening 9pm through 7am
  ingressHost: em-hrs-ingestor-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: em
  suspend: false
  #override to suspend future cron jobs
  concurrencyPolicy: Forbid
  keyVaults:
    rpa:
      resourceGroup: rpa
      secrets:
        - AppInsightsInstrumentationKey
    em-hrs-ingestor:
      resourceGroup: em-hrs-ingestor
      secrets:
        - microservicekey-em-hrs-ingestor
    em-hrs-api:
      resourceGroup: em-hrs-api
      secrets:
        - cvp-storage-connection-string
        - cvp-storage-container-name
  environment:
    S2S_BASE_URI: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    HRS_API_BASE_URI: http://em-hrs-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    JSON_CONSOLE_PRETTY_PRINT: false
    LOG_OUTPUT: single
    ROOT_LOGGING_LEVEL: INFO
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_DM: INFO
    SHOW_SQL: false

global:
  jobKind: CronJob
