---
s2s.hrs.api.url: http://localhost:8088

idam:
  hrs-ingestor:
    user-name: ${IDAM_HRS_INGESTOR_SYSTEM_USER_NAME:test}
    password: ${IDAM_HRS_INGESTOR_SYSTEM_PASSWORD:AAAAAAAAAAAAAAAA}
  api:
    url: http://localhost-idam:8090
    client:
      cache:
        refresh-before-expire-in-sec: 300
