---
s2s.hrs.api.url: http://localhost:8088

ingestion:
  vh:
    process: true
    max-blob-process-count: 200
idam:
  hrs-ingestor:
    user-name: ${IDAM_HRS_INGESTOR_USER_NAME:test}
    password: ${IDAM_HRS_INGESTOR_PASSWORD:AAAAAAAAAAAAAAAA}
  api:
    url: http://localhost-idam:8090
